### PR TITLE
Clean up Yale Schema

### PR DESCRIPTION
**Pull request by graphemecluster**
The ordering of the rules are tested carefully.

Additional changes are discouraged – any removal of rules or change of characters or ordering may break the schema.

(`z → dz`, `c → ts` are moved to the bottom.)

### CODE REVIEW

**Comment by alex-the-man** [comment]
@sdugoten Would you mind providing some user feedback after I merge this PR? Thanks.

**Comment by sdugoten** [comment]
Hi, other than the marked text behavior, I don't see any issue so far.  Please go ahead and push this to a release version.  I will report when I encounter more issue as I use Cantoboard on a daily basis now.  Thanks.

**Comment by graphemecluster** [comment]
Does the typing experience improve? Anything changed for the worse?

**Comment by alex-the-man** [comment]
Sorry please give me some time to release the new Test Flight build. I'm doing a lot of refactoring locally to better support iPad.

**Pull request merged**
