### PR TITLE
Add keyboard assets

### PR DESCRIPTION
**Pull request by graphemecluster**
- Show placeholder keys with keys disabled instead of hide them
- Merge `face.smiling.fill` to `face.smiling` asset by using appearance variation "Any, Dark"
- Add `delete.left.fill`, `clear.fill`, `arrow.right.to.line`, `return.left`, `keyHighlightedShadowColor`, `placeholderKeyForegroundColor` and `keyGrayedColor` assets
- Add `keyboardBackgroundColor` asset for test app

### CODE REVIEW

**Comment by alex-the-man** [comment]
Could you rebase and remove commit "Fix insert composing text to use partially selected rime composition"?

**Comment by alex-the-man** [comment]
> Show placeholder keys with keys disabled instead of hide them

The default iOS keyboard hides them instead of showing them. Should we keep that behaviour?

**Comment by graphemecluster** [comment]
Screenshot

**Comment by graphemecluster** [comment]
Completed.

**Comment by alex-the-man** [comment]
For some reason, the dark emoji isn't showing face.smiling.fill for me
image

**Comment by graphemecluster** [comment]
> For some reason, the dark emoji isn't showing face.smiling.fill for me

Fallback to the original method then.

**Pull request merged**
